# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0197d78df38c3def40a577e1fdcd27ec"
application_url = "https://talecommerce.github.io/shop-custom-app-auth?client_id=0197d78df38c3def40a577e1fdcd27ec"
embedded = true
name = "lannoo-discount-validation-app"
handle = "lannoo-discount-validation-app"
extension_directories = [
    "extensions/product-updated",
    "extensions/sample-copy-discount-function"
]

[build]
include_config_on_deploy = true
dev_store_url = "lannoo-meulenhoff-dev.myshopify.com"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products, read_orders, write_orders, read_customers, write_customers, read_discounts, write_discounts, read_price_rules, write_price_rules, write_cart_transforms, write_delivery_customizations"


[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth", "https://talecommerce.github.io/shop-custom-app-auth" ]

[pos]
embedded = false
