[[extensions]]
name = "Trigger Product Updated"
type = "flow_trigger"
handle = "trigger-product-updated"
description = "Trigger a flow when a product's has_sample_copy metafield is updated"

[settings]

  [[settings.fields]]
  type = "product_reference"
  description = "The product whose metafield was updated."